header:
 
  - titles:
      # @start locale config
      en      : &EN       Dubbo
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  Dubbo
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  Dubbo
      zh-TW   : *ZH_HANT
    url: /dubbo.html
 
  - titles:
      # @start locale config
      en      : &EN       Spring
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  Spring
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  Spring
      zh-TW   : *ZH_HANT
    url: /spring.html   
    
  - titles:
      # @start locale config
      zh-Hans : &ZH_HANS  SpringMVC
    url: /springmvc.html  

  - titles:
      # @start locale config
      en      : &EN       Spring Boot
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  Spring Boot
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  Spring Boot
      zh-TW   : *ZH_HANT
    url: /springboot.html   
    
  - titles:
      # @start locale config
      en      : &EN       Spring Cloud
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  Spring Cloud
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  Spring Cloud
      zh-TW   : *ZH_HANT
    url: /springcloud.html   
    
  - titles:
      # @start locale config
      en      : &EN       Archive
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  归档
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  歸檔
      zh-TW   : *ZH_HANT
      zh-HK   : *ZH_HANT
      ko      : &KO       아카이브
      ko-KR   : *KO
      fr      : &FR       Archives
      fr-BE   : *FR
      fr-CA   : *FR
      fr-CH   : *FR
      fr-FR   : *FR
      fr-LU   : *FR
      # @end locale config
    url: /archive.html

  - titles:
      # @start locale config
      en      : &EN       About
      en-GB   : *EN
      en-US   : *EN
      en-CA   : *EN
      en-AU   : *EN
      zh-Hans : &ZH_HANS  关于
      zh      : *ZH_HANS
      zh-CN   : *ZH_HANS
      zh-SG   : *ZH_HANS
      zh-Hant : &ZH_HANT  關於
      zh-TW   : *ZH_HANT
      zh-HK   : *ZH_HANT
      ko      : &KO       소개
      ko-KR   : *KO
      fr      : &KO       À propos
      fr-BE   : *FR
      fr-CA   : *FR
      fr-CH   : *FR
      fr-FR   : *FR
      fr-LU   : *FR
      # @end locale config
    url: /about.html
   

dubbo:
  - title: Dubbo教程
    children:
      - title: 1.Dubbo的基础配置
        url: https://javamans.github.io/2020/01/14/dubbo.html
      - title: 2.Dubbo的示例
        url: https://javamans.github.io/2020/01/16/dubbo.html
      - title: 3.Dubbo SPI机制原理
        url: https://javamans.github.io/2020/01/18/dubbo.html
        
spring:
  - title: Spring源码分析
    children:
      - title: 1.Spring容器加载方式和XML解析流程
        url: https://javamans.github.io/2020/01/01/spring.html
      - title: 2.Spring源码中Beandefinition对象
        url: https://javamans.github.io/2020/01/02/spring.html
      - title: 3.Spring源码中默认标签的解析
        url: https://javamans.github.io/2020/01/03/spring.html
      - title: 4.Spring源码中自定义标签的解析
        url: https://javamans.github.io/2020/01/04/spring.html
      - title: 5.Spring源码中BeanDefinitionRegistryPostProcessor接口
        url: https://javamans.github.io/2020/01/05/spring.html
      - title: 6.Spring源码中BeanPostProcessor接口
        url: https://javamans.github.io/2020/01/06/spring.html
      - title: 7.Spring源码中Bean实例化过程
        url: https://javamans.github.io/2020/01/07/spring.html
      - title: 8.Spring源码中createBean方法
        url: https://javamans.github.io/2020/01/08/spring.html
      - title: 9.Spring源码中Bean实例化核心方法createBeanInstance
        url: https://javamans.github.io/2020/01/09/spring.html
      - title: 10.Spring源码对类中注解的装配过程
        url: https://javamans.github.io/2020/01/10/spring.html
      - title: 11.Spring源码中依赖注入populateBean
        url: https://javamans.github.io/2020/01/11/spring.html  
      - title: 12.Spring源码中bean实例化后的操作initializeBean 
        url: https://javamans.github.io/2020/01/12/spring.html  
      - title: 13.Spring源码中注册Bean销毁时的类DisposableBeanAdapter 
        url: https://javamans.github.io/2020/01/13/spring.html 
      - title: 14.Spring循环依赖
        url: https://javamans.github.io/2020/01/14/spring.html 
      - title: 15.Spring源码中BeanPostProcessor接口的理解
        url: https://javamans.github.io/2020/01/14/spring.html 
        
        
        

       
        